import type { LinkBatchAction, LinkBatchResponse, LinkListResponse, LinkRecord } from './types.mjs';

export const MAX_LINK_PATH_LENGTH: 128;
export const MAX_TARGET_URL_LENGTH: 4096;
export const DEFAULT_LIST_LIMIT: 25;
export const MAX_LIST_LIMIT: 100;
export const MAX_BATCH_SIZE: 50;
export const MAX_CURSOR_LENGTH: 2048;
export const LINK_BATCH_ACTIONS: readonly LinkBatchAction[];
export const LINK_STATUS_CODES: readonly (301 | 302)[];
export const LINK_MATCHES: readonly string[];
export const LINK_STATES: readonly string[];
export const LINK_SORTS: readonly string[];
export const LINK_VIEWS: readonly string[];
export const LINK_QUERY_KEYS: readonly string[];
export function isLinkBatchAction(value: unknown): value is LinkBatchAction;
export function isLinkStatusCode(value: unknown): value is 301 | 302;
export function isLinkMatch(value: unknown): boolean;
export function isLinkState(value: unknown): boolean;
export function isLinkSort(value: unknown): boolean;
export function isLinkView(value: unknown): boolean;
export function normalizeLinkPath(input: unknown): string;
export function normalizeLinkPrefix(input: unknown): string;
export type LinkPathIssue = 'required' | 'length' | 'dot_segments' | 'double_slash' | 'query_fragment';
export function linkPathIssue(input: unknown, options?: { prefix?: boolean }): LinkPathIssue | null;
export type TargetUrlIssue = 'type' | 'required' | 'length' | 'invalid' | 'protocol' | 'credentials' | 'query_fragment';
export function targetUrlIssue(value: unknown): TargetUrlIssue | null;
export function splitTargetUrl(value: string): { targetUrl: string; targetBaseUrl: string; targetPath: string };
export function isSubdomainLength(value: unknown): boolean;
export function isLinkRecord(value: unknown): value is LinkRecord;
export function linkListResponse(items: LinkRecord[], nextCursor: string | null): LinkListResponse;
export function linkBatchResponse(action: LinkBatchAction, succeeded: LinkBatchResponse['succeeded'], failed: LinkBatchResponse['failed']): LinkBatchResponse;
export function parseLinkListResponse(value: unknown): LinkListResponse | null;
export function parseLinkBatchResponse(value: unknown): LinkBatchResponse | null;
export function normalizePublicRequestPath(rawPath: unknown): string;
export function requestPath(event: unknown): string;
